# Generated by Django 3.0.6 on 2020-05-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
