# Generated by Django 3.0.6 on 2020-05-09 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20200508_0403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('person', 'group')},
        ),
    ]
